services:
  api-1:
    image: rpxc/fraud-detector-api:04fc28e
    environment:
      - INSTANCE_ID=1
      - GOMAXPROCS=1
      - GOMEMLIMIT=140MiB
      - GOGC=150
    networks:
      - rinha-net
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "145MB"

  api-2:
    image: rpxc/fraud-detector-api:04fc28e
    environment:
      - INSTANCE_ID=2
      - GOMAXPROCS=1
      - GOMEMLIMIT=140MiB
      - GOGC=150
    networks:
      - rinha-net
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "145MB"

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-1
      - api-2
    networks:
      - rinha-net
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "45MB"

networks:
  rinha-net:
    driver: bridge
