services:
  api-1:
    build:
      context: .
      dockerfile: api/Dockerfile
    image: rpxc/fraud-detector-api:latest
    environment:
      - INSTANCE_ID=1
      - RINHA_SOCKET=/sockets/api1.sock
      - GOMAXPROCS=1
      - GOMEMLIMIT=150MiB
      - GOGC=200
    volumes:
      - sockets:/sockets
    networks:
      - rinha-net
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "160MB"

  api-2:
    build:
      context: .
      dockerfile: api/Dockerfile
    image: rpxc/fraud-detector-api:latest
    environment:
      - INSTANCE_ID=2
      - RINHA_SOCKET=/sockets/api2.sock
      - GOMAXPROCS=1
      - GOMEMLIMIT=150MiB
      - GOGC=200
    volumes:
      - sockets:/sockets
    networks:
      - rinha-net
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "160MB"

  lb:
    build:
      context: .
      dockerfile: api/lb/Dockerfile
    image: rpxc/fraud-detector-lb:latest
    ports:
      - "9999:9999"
    environment:
      - LB_ADDR=0.0.0.0:9999
      - LB_UPSTREAMS=/sockets/api1.sock,/sockets/api2.sock
    volumes:
      - sockets:/sockets
    depends_on:
      - api-1
      - api-2
    networks:
      - rinha-net
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "30MB"

networks:
  rinha-net:
    driver: bridge

volumes:
  sockets:
